### ISSUE TITLE
Security consideration

### ISSUE THREAD

**Issue by vcarus** [marcoroth/ShortLook-Telegram#1]
I'm looking for a Telegram addons. And luckily find your project.

It works good. But pardon my words, idk if it's safe to use.

In TelegramContactPhotoProvider.m
Core function is like below
https://shortlook-telegram.herokuapp.com/profile-picture/%@?key=%@

Is the URL coming from official or something?
Or somehow I can make a server side of my own?

Thanks.

**Comment by marcoroth** [comment]
Hey vcarus

Thanks for reaching out.

It's not an official Telegram endpoint, it's a little Ruby Web-Server I've put together using the Telegram Bot API. You can see the source code in the repo below. You can easily host it yourself on Heroku if you want to.
https://github.com/marcoroth/telegram-profile-picture

Sadly, it's not a very satisfying solution since the profile picture is only visible to the bot if the user explicitly messages the bot. Like this, every user needs to message the bot in order to show his profile picture in ShortLook.

I've you got a better idea please let me know.

Cheers
Marco

**Comment by vcarus** [comment]
Thanks Marco. 

I'll see if anything can make a better solution.
Wish you a good day~

vcarus
